// Bloghead Profile Options - All options in German
// Used for profile editing forms

export const GENRE_OPTIONS = [
  { value: 'pop', label: 'Pop' },
  { value: 'rock', label: 'Rock' },
  { value: 'hip-hop', label: 'Hip-Hop' },
  { value: 'rap', label: 'Rap' },
  { value: 'rnb', label: 'R&B' },
  { value: 'house', label: 'House' },
  { value: 'techno', label: 'Techno' },
  { value: 'electronic', label: 'Elektronisch' },
  { value: 'edm', label: 'EDM' },
  { value: 'trance', label: 'Trance' },
  { value: 'dnb', label: 'Drum & Bass' },
  { value: 'dubstep', label: 'Dubstep' },
  { value: 'jazz', label: 'Jazz' },
  { value: 'blues', label: 'Blues' },
  { value: 'soul', label: 'Soul' },
  { value: 'funk', label: 'Funk' },
  { value: 'reggae', label: 'Reggae' },
  { value: 'latin', label: 'Latin' },
  { value: 'salsa', label: 'Salsa' },
  { value: 'bachata', label: 'Bachata' },
  { value: 'schlager', label: 'Schlager' },
  { value: 'volksmusik', label: 'Volksmusik' },
  { value: 'classical', label: 'Klassik' },
  { value: 'opera', label: 'Oper' },
  { value: 'metal', label: 'Metal' },
  { value: 'punk', label: 'Punk' },
  { value: 'indie', label: 'Indie' },
  { value: 'alternative', label: 'Alternative' },
  { value: 'country', label: 'Country' },
  { value: 'folk', label: 'Folk' },
  { value: 'acoustic', label: 'Akustik' },
  { value: 'singer-songwriter', label: 'Singer-Songwriter' },
  { value: 'world', label: 'Weltmusik' },
  { value: 'afrobeat', label: 'Afrobeat' },
  { value: 'dancehall', label: 'Dancehall' },
  { value: 'trap', label: 'Trap' },
  { value: 'kpop', label: 'K-Pop' },
  { value: 'lounge', label: 'Lounge' },
  { value: 'chill', label: 'Chill' },
  { value: 'ambient', label: 'Ambient' },
] as const

export const SERVICE_CATEGORY_OPTIONS = [
  { value: 'catering', label: 'Catering' },
  { value: 'photography', label: 'Fotografie' },
  { value: 'videography', label: 'Videografie' },
  { value: 'decoration', label: 'Dekoration' },
  { value: 'florist', label: 'Floristik' },
  { value: 'lighting', label: 'Beleuchtung' },
  { value: 'sound', label: 'Tontechnik' },
  { value: 'stage', label: 'Bühnentechnik' },
  { value: 'security', label: 'Sicherheitsdienst' },
  { value: 'entertainment', label: 'Entertainment' },
  { value: 'moderation', label: 'Moderation' },
  { value: 'makeup', label: 'Make-up & Styling' },
  { value: 'hair', label: 'Friseur' },
  { value: 'transport', label: 'Transport & Logistik' },
  { value: 'rental', label: 'Verleih & Vermietung' },
  { value: 'furniture', label: 'Möbel & Ausstattung' },
  { value: 'tent', label: 'Zelte & Pavillons' },
  { value: 'bar', label: 'Barkeeper & Cocktails' },
  { value: 'staff', label: 'Personal & Service' },
  { value: 'cleaning', label: 'Reinigung' },
  { value: 'printing', label: 'Druckerei & Grafik' },
  { value: 'invitation', label: 'Einladungen & Papeterie' },
  { value: 'wedding-planner', label: 'Hochzeitsplaner' },
  { value: 'event-planner', label: 'Eventplaner' },
  { value: 'fireworks', label: 'Feuerwerk & Pyrotechnik' },
  { value: 'photo-booth', label: 'Fotobox & Photobooth' },
  { value: 'games', label: 'Spiele & Animation' },
  { value: 'kids', label: 'Kinderbetreuung' },
  { value: 'performer', label: 'Showacts & Performer' },
  { value: 'magician', label: 'Zauberer & Illusionist' },
  { value: 'comedian', label: 'Comedian' },
  { value: 'dance', label: 'Tanzgruppen' },
  { value: 'acrobat', label: 'Akrobatik' },
  { value: 'other', label: 'Sonstiges' },
] as const

export const EVENT_TYPE_OPTIONS = [
  { value: 'wedding', label: 'Hochzeit' },
  { value: 'birthday', label: 'Geburtstag' },
  { value: 'corporate', label: 'Firmenfeier' },
  { value: 'conference', label: 'Konferenz' },
  { value: 'gala', label: 'Gala' },
  { value: 'festival', label: 'Festival' },
  { value: 'concert', label: 'Konzert' },
  { value: 'club', label: 'Club-Event' },
  { value: 'party', label: 'Party' },
  { value: 'private', label: 'Privatfeier' },
  { value: 'graduation', label: 'Abschlussfeier' },
  { value: 'anniversary', label: 'Jubiläum' },
  { value: 'christmas', label: 'Weihnachtsfeier' },
  { value: 'new-year', label: 'Silvester' },
  { value: 'summer', label: 'Sommerfest' },
  { value: 'garden', label: 'Gartenparty' },
  { value: 'brunch', label: 'Brunch' },
  { value: 'dinner', label: 'Dinner-Event' },
  { value: 'cocktail', label: 'Cocktail-Empfang' },
  { value: 'networking', label: 'Networking-Event' },
  { value: 'product-launch', label: 'Produktpräsentation' },
  { value: 'opening', label: 'Eröffnung' },
  { value: 'vernissage', label: 'Vernissage' },
  { value: 'fashion', label: 'Modenschau' },
  { value: 'charity', label: 'Charity-Event' },
  { value: 'sports', label: 'Sportveranstaltung' },
  { value: 'team-building', label: 'Team-Building' },
  { value: 'workshop', label: 'Workshop' },
  { value: 'seminar', label: 'Seminar' },
  { value: 'trade-fair', label: 'Messe' },
  { value: 'exhibition', label: 'Ausstellung' },
  { value: 'other', label: 'Sonstiges' },
] as const

export const EQUIPMENT_OPTIONS = [
  { value: 'pa-system', label: 'PA-Anlage' },
  { value: 'mixer', label: 'Mischpult' },
  { value: 'dj-controller', label: 'DJ-Controller' },
  { value: 'turntables', label: 'Plattenspieler' },
  { value: 'cdj', label: 'CDJ-Player' },
  { value: 'microphone', label: 'Mikrofon' },
  { value: 'wireless-mic', label: 'Funkmikrofon' },
  { value: 'headphones', label: 'Kopfhörer' },
  { value: 'speakers', label: 'Lautsprecher' },
  { value: 'subwoofer', label: 'Subwoofer' },
  { value: 'monitors', label: 'Monitorboxen' },
  { value: 'amplifier', label: 'Verstärker' },
  { value: 'laptop', label: 'Laptop' },
  { value: 'cables', label: 'Kabel & Verbindungen' },
  { value: 'stand', label: 'Ständer' },
  { value: 'lighting', label: 'Beleuchtung' },
  { value: 'moving-heads', label: 'Moving Heads' },
  { value: 'led-par', label: 'LED Par' },
  { value: 'laser', label: 'Laser' },
  { value: 'fog-machine', label: 'Nebelmaschine' },
  { value: 'strobe', label: 'Stroboskop' },
  { value: 'dmx-controller', label: 'DMX-Controller' },
  { value: 'generator', label: 'Stromgenerator' },
  { value: 'booth', label: 'DJ-Booth' },
  { value: 'truss', label: 'Traversen' },
  { value: 'screen', label: 'Leinwand/Screen' },
  { value: 'projector', label: 'Beamer/Projektor' },
  { value: 'led-wall', label: 'LED-Wand' },
] as const

export const AMENITY_OPTIONS = [
  { value: 'parking', label: 'Parkplätze' },
  { value: 'valet', label: 'Parkservice' },
  { value: 'wifi', label: 'WLAN' },
  { value: 'stage', label: 'Bühne' },
  { value: 'dance-floor', label: 'Tanzfläche' },
  { value: 'outdoor-area', label: 'Außenbereich' },
  { value: 'terrace', label: 'Terrasse' },
  { value: 'garden', label: 'Garten' },
  { value: 'rooftop', label: 'Dachterrasse' },
  { value: 'vip-area', label: 'VIP-Bereich' },
  { value: 'lounge', label: 'Lounge-Bereich' },
  { value: 'bar', label: 'Bar' },
  { value: 'kitchen', label: 'Küche' },
  { value: 'catering-kitchen', label: 'Cateringküche' },
  { value: 'cloakroom', label: 'Garderobe' },
  { value: 'wheelchair', label: 'Barrierefrei' },
  { value: 'elevator', label: 'Aufzug' },
  { value: 'ac', label: 'Klimaanlage' },
  { value: 'heating', label: 'Heizung' },
  { value: 'sound-system', label: 'Soundanlage' },
  { value: 'lighting-system', label: 'Lichtanlage' },
  { value: 'projector', label: 'Beamer' },
  { value: 'screen', label: 'Leinwand' },
  { value: 'furniture', label: 'Möblierung' },
  { value: 'tables', label: 'Tische' },
  { value: 'chairs', label: 'Stühle' },
  { value: 'decoration', label: 'Dekoration' },
  { value: 'bridal-suite', label: 'Brautsuite' },
  { value: 'changing-room', label: 'Umkleide' },
  { value: 'restrooms', label: 'Toiletten' },
  { value: 'smoking-area', label: 'Raucherbereich' },
  { value: 'catering-included', label: 'Catering inklusive' },
  { value: 'drinks-included', label: 'Getränke inklusive' },
  { value: 'security', label: 'Sicherheitsdienst' },
  { value: 'staff', label: 'Servicepersonal' },
  { value: 'overnight', label: 'Übernachtung möglich' },
] as const

export const LANGUAGE_OPTIONS = [
  { value: 'de', label: 'Deutsch' },
  { value: 'en', label: 'Englisch' },
  { value: 'fr', label: 'Französisch' },
  { value: 'es', label: 'Spanisch' },
  { value: 'it', label: 'Italienisch' },
  { value: 'pt', label: 'Portugiesisch' },
  { value: 'nl', label: 'Niederländisch' },
  { value: 'pl', label: 'Polnisch' },
  { value: 'ru', label: 'Russisch' },
  { value: 'tr', label: 'Türkisch' },
  { value: 'ar', label: 'Arabisch' },
  { value: 'zh', label: 'Chinesisch' },
  { value: 'ja', label: 'Japanisch' },
  { value: 'ko', label: 'Koreanisch' },
  { value: 'hi', label: 'Hindi' },
  { value: 'other', label: 'Andere' },
] as const

export const EXPERIENCE_LEVEL_OPTIONS = [
  { value: 'beginner', label: 'Anfänger (0-2 Jahre)' },
  { value: 'intermediate', label: 'Fortgeschritten (2-5 Jahre)' },
  { value: 'professional', label: 'Profi (5-10 Jahre)' },
  { value: 'expert', label: 'Experte (10+ Jahre)' },
] as const

export const AVAILABILITY_OPTIONS = [
  { value: 'weekdays', label: 'Wochentags' },
  { value: 'weekends', label: 'Wochenende' },
  { value: 'evenings', label: 'Abends' },
  { value: 'mornings', label: 'Vormittags' },
  { value: 'afternoons', label: 'Nachmittags' },
  { value: 'nights', label: 'Nachts' },
  { value: 'holidays', label: 'Feiertage' },
  { value: 'flexible', label: 'Flexibel' },
] as const

export const TRAVEL_RADIUS_OPTIONS = [
  { value: '10', label: 'bis 10 km' },
  { value: '25', label: 'bis 25 km' },
  { value: '50', label: 'bis 50 km' },
  { value: '100', label: 'bis 100 km' },
  { value: '200', label: 'bis 200 km' },
  { value: 'nationwide', label: 'Deutschlandweit' },
  { value: 'international', label: 'International' },
] as const

export const VENUE_TYPE_OPTIONS = [
  { value: 'club', label: 'Club' },
  { value: 'bar', label: 'Bar' },
  { value: 'lounge', label: 'Lounge' },
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'hotel', label: 'Hotel' },
  { value: 'conference', label: 'Konferenzraum' },
  { value: 'ballroom', label: 'Ballsaal' },
  { value: 'banquet', label: 'Bankettsaal' },
  { value: 'outdoor', label: 'Open Air' },
  { value: 'beach', label: 'Strandclub' },
  { value: 'rooftop', label: 'Rooftop' },
  { value: 'warehouse', label: 'Warehouse/Halle' },
  { value: 'castle', label: 'Schloss/Burg' },
  { value: 'vineyard', label: 'Weingut' },
  { value: 'garden', label: 'Garten/Park' },
  { value: 'ship', label: 'Schiff' },
  { value: 'theater', label: 'Theater' },
  { value: 'gallery', label: 'Galerie' },
  { value: 'studio', label: 'Studio' },
  { value: 'private', label: 'Privathaus' },
  { value: 'other', label: 'Sonstiges' },
] as const

export const PAYMENT_METHOD_OPTIONS = [
  { value: 'cash', label: 'Barzahlung' },
  { value: 'bank-transfer', label: 'Überweisung' },
  { value: 'paypal', label: 'PayPal' },
  { value: 'credit-card', label: 'Kreditkarte' },
  { value: 'debit-card', label: 'EC-Karte' },
  { value: 'invoice', label: 'Rechnung' },
] as const

export const SOCIAL_PLATFORM_OPTIONS = [
  { value: 'instagram', label: 'Instagram', icon: 'instagram', placeholder: '@benutzername' },
  { value: 'facebook', label: 'Facebook', icon: 'facebook', placeholder: 'facebook.com/...' },
  { value: 'tiktok', label: 'TikTok', icon: 'tiktok', placeholder: '@benutzername' },
  { value: 'youtube', label: 'YouTube', icon: 'youtube', placeholder: 'youtube.com/@...' },
  { value: 'twitter', label: 'X (Twitter)', icon: 'twitter', placeholder: '@benutzername' },
  { value: 'spotify', label: 'Spotify', icon: 'spotify', placeholder: 'Spotify Artist Link' },
  { value: 'soundcloud', label: 'SoundCloud', icon: 'soundcloud', placeholder: 'soundcloud.com/...' },
  { value: 'mixcloud', label: 'Mixcloud', icon: 'mixcloud', placeholder: 'mixcloud.com/...' },
  { value: 'bandcamp', label: 'Bandcamp', icon: 'bandcamp', placeholder: '...bandcamp.com' },
  { value: 'linkedin', label: 'LinkedIn', icon: 'linkedin', placeholder: 'linkedin.com/in/...' },
  { value: 'website', label: 'Webseite', icon: 'globe', placeholder: 'https://...' },
] as const

// German cities for location autocomplete
export const GERMAN_CITIES = [
  'Berlin', 'Hamburg', 'München', 'Köln', 'Frankfurt am Main', 'Stuttgart',
  'Düsseldorf', 'Leipzig', 'Dortmund', 'Essen', 'Bremen', 'Dresden',
  'Hannover', 'Nürnberg', 'Duisburg', 'Bochum', 'Wuppertal', 'Bielefeld',
  'Bonn', 'Münster', 'Mannheim', 'Karlsruhe', 'Augsburg', 'Wiesbaden',
  'Mainz', 'Freiburg im Breisgau', 'Heidelberg', 'Darmstadt', 'Kassel',
  'Kiel', 'Magdeburg', 'Aachen', 'Braunschweig', 'Chemnitz', 'Krefeld',
  'Halle (Saale)', 'Rostock', 'Erfurt', 'Saarbrücken', 'Potsdam',
  'Lübeck', 'Oldenburg', 'Osnabrück', 'Würzburg', 'Regensburg',
  'Wolfsburg', 'Ingolstadt', 'Ulm', 'Heilbronn', 'Göttingen',
] as const

// Type exports for TypeScript
export type GenreOption = typeof GENRE_OPTIONS[number]
export type ServiceCategoryOption = typeof SERVICE_CATEGORY_OPTIONS[number]
export type EventTypeOption = typeof EVENT_TYPE_OPTIONS[number]
export type EquipmentOption = typeof EQUIPMENT_OPTIONS[number]
export type AmenityOption = typeof AMENITY_OPTIONS[number]
export type LanguageOption = typeof LANGUAGE_OPTIONS[number]
export type ExperienceLevelOption = typeof EXPERIENCE_LEVEL_OPTIONS[number]
export type AvailabilityOption = typeof AVAILABILITY_OPTIONS[number]
export type TravelRadiusOption = typeof TRAVEL_RADIUS_OPTIONS[number]
export type VenueTypeOption = typeof VENUE_TYPE_OPTIONS[number]
export type PaymentMethodOption = typeof PAYMENT_METHOD_OPTIONS[number]
export type SocialPlatformOption = typeof SOCIAL_PLATFORM_OPTIONS[number]
